services:
  adminivoire.webapi:
    image: ${DOCKER_REGISTRY-}adminivoirewebapi
    container_name: adminivoire.webapi
    build:
      context: .
      dockerfile: AdminIvoire.WebApi/Dockerfile
    ports:
        - "8080:8080"
        - "8081:8081"
    depends_on:
        - adminivoire.db
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ConnectionStrings__LocaliteContext=Host=adminivoire.db;Database=adminivoire;Username=adminivoire;Password=${POSTGRES_PASSWORD};Port=5432
        - GoogleMaps__ApiKey=${GOOGLEMAPS_APIKEY}
    networks:
        - adminivoire

  
  adminivoire.db:
    image: postgres
    container_name: adminivoire.db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
        - "5432:5432"
    volumes:
        - adminivoire.db-data:/var/lib/postgresql/data
    networks:
        - adminivoire

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: adminivoire.keycloak
    command: start-dev
    environment:
       - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
       - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
       - KC_HEALTH_ENABLED=true
    volumes:
       - ./.containers/identity:/opt/keycloak/data
    ports:
       - "18080:8080" 
    networks:
       - adminivoire

networks:
      adminivoire:

volumes:
    adminivoire.db-data:
