services:
  adminivoire.webapi:
    image: ${DOCKER_REGISTRY-}adminivoirewebapi
    container_name: adminivoire.webapi
    build:
      context: .
      dockerfile: AdminIvoire.WebApi/Dockerfile
    ports:
        - "8080:8080"
        - "8081:8081"
    depends_on:
        - adminivoire.db
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - POSTGRES_DB=${POSTGRES_DB:-adminivoire}
    secrets:
        - postgres_password
        - postgres_user
        - googlemaps_apikey
    networks:
        - adminivoire

  
  adminivoire.db:
    image: postgres
    container_name: adminivoire.db
    restart: always
    entrypoint: ["/bin/bash", "-c", "export POSTGRES_USER=$$(cat /run/secrets/postgres_user) && export POSTGRES_PASSWORD=$$(cat /run/secrets/postgres_password) && exec /usr/local/bin/docker-entrypoint.sh postgres"]
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
    secrets:
        - postgres_user
        - postgres_password
    ports:
        - "5432:5432"
    volumes:
        - adminivoire.db-data:/var/lib/postgresql/data
    networks:
        - adminivoire

secrets:
    postgres_user:
        file: ./secrets/postgres_user.txt
    postgres_password:
        file: ./secrets/postgres_password.txt
    googlemaps_apikey:
        file: ./secrets/googlemaps_apikey.txt

networks:
      adminivoire:

volumes:
    adminivoire.db-data:
